# Generated by Django 4.0.3 on 2022-03-14 13:26

import blocks.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuspage',
            name='content',
            field=wagtail.core.fields.StreamField([('simple_banner', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True))])), ('simple_richtext', blocks.blocks.SimpleRichtextBlock())], blank=True, null=True),
        ),
    ]
