# Generated by Django 4.0.3 on 2022-03-14 13:48

import blocks.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0002_alter_aboutuspage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuspage',
            name='content',
            field=wagtail.core.fields.StreamField([('simple_banner', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True))])), ('simple_richtext', blocks.blocks.SimpleRichtextBlock()), ('card_blocks', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.core.blocks.CharBlock(max_length=40, required=True)), ('text', wagtail.core.blocks.TextBlock(required=True)), ('url_button', wagtail.core.blocks.URLBlock(required=False))])))]))], blank=True, null=True),
        ),
    ]
