# Generated by Django 4.0.3 on 2022-03-16 08:19

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='content',
            field=wagtail.core.fields.StreamField([('drop_down', wagtail.core.blocks.StructBlock([('drop_down', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('link_title', wagtail.core.blocks.CharBlock(max_length=40, required=True)), ('link_page', wagtail.core.blocks.PageChooserBlock(required=False))])))]))], blank=True, null=True),
        ),
    ]
